- app/globals.css
- tailwind.config.ts
- 폰트는 Pretendard로 자동 적용됩니다.
- Tailwind CSS IntelliSense 확장 프로그램에서 설치하면 자동완성 기능을 사용할 수 있습니다.
> feat: global.css 스타일 추가

- .prettierrc
- eslint.config.mjs
prettierrc eslint.config.mjs 파일 추가 및 1차 수정
> Add: eslint & prettier initial setup

- README.md
현재 정해진 정보를 바탕으로 readme 작성하였습니다. 
Q. 문의사항이 있습니다. 
이번 프로젝트에서 인증 방식은 어떤 것일까요? next auth 같은 외부 라이브러리를 사용하나요? 
확인 부탁드립니다!
> README 내용 업데이트 

- app/globals.css
- components/common/DatePicker.tsx
- package-lock.json
- package.json
- 이슈 번호
---
datepicker 공통 컴포넌트 구현 
---
> 어떤 작업을 했고, 왜 했는지 요약
- **react-day-picker , date-fns 라이브러리 설치**
- daypicker UI 구현
- 
---
- - `selected`
- 선택된 날짜를 설정한다
- 타입 : Date | Date[] | undefined
- 예시 →사용자가 날짜를 클릭하면 해당 날짜가 selected 값으로 반영됩니다.
- `onSelect`
- 날짜를 선택할 때 호출되는 콜백  함수
- 선택된 날짜를 state에 저장하는 데 사용
- `showOutsideDays`
- 이전 달, 다음 달의 날짜도 현재 달 달력에 표시한다.
- `locale`
- 달력에 사용할 언어 및 지역 정보를 설정
- enUs, ko 등 다양한 locale을 설정할 수 있고, `date-fns`에서 제공하는 locale 객체를 사용합니다.
```jsx
import {enUS} from 'date-fns/locale'
```
- `classNames`
- DayPicker의 각 부분에 대해 Tailwind로 스타일을 커스터마이징 한다.
- `nav` : 네비게이션 영역 (이전/다음 달 버튼)
- `caption` : 달의 제목 영역 (May 2025)
- `weekday` : 요일 텍스트
- `day` : 각 날짜 셀
- `modifiersClassNames`
- 특성 상태(선택됨, 오늘, outside 등)인 날짜에 조건부 클래스를 부여한다.
- `selected` : 선택된 날짜
- `today` : 오늘 날짜
- …
> [Feat] DatePicker 구현

- app/layout.tsx
- components/common/ModalTest.tsx
- package-lock.json
- store/OneButtonModalStore.tsx
- 이슈 번호
---
---
> 어떤 작업을 했고, 왜 했는지 요약
- twoButton 버튼 모달 생성 및 기존 원 버튼 모달은 확인 버튼을 누르면 닫는 기능만 하였는데 함수를 넣고 닫는 기능이 되는 부분을 보안하였음
---
- (어떤 기능 구현했는지)
twoButton 버튼 모달 생성 및 기존 원 버튼 모달은 확인 버튼을 누르면 닫는 기능만 하였는데 함수를 넣고 닫는 기능이 되는 부분을 보안하였음
---
> UI 작업한 경우 추가
| 기능       | 스크린샷              |
| ---------- | --------------------- |
| 팀 생성 폼 | ![image](이미지 주소) |
---
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
- (전달 사항)
app-> page.tsx파일에 스크린샷 처럼 코드를 작성하고 테스트 해 볼 수 있습니다 ModalTest.tsx에  어떤식인지 대략 나와있음
---
> [Feat] 버튼 2개 모달 생성 및 버튼 한개 모달의 기능 추가 구현 

- .gitignore
- .storybook/main.ts
- .storybook/preview.ts
- components/stories/CommonButton.stories.tsx
- components/stories/DatePicker.stories.tsx
- components/stories/DropDown.stories.tsx
- components/stories/DropDownSelect.stories.tsx
- components/stories/Footer.stories.tsx
- components/stories/Input.stories.tsx
- package.json
> 스토리북 설치, 설정 변경, 스토리북 컴포넌트 추가
- package.json 파일 수정하였습니다. npm install 필요합니다. 
- develop 과 파일 충돌이 생겨서, fetch로 업데이트 하고, 충돌 내용 수정 하던 중 package-lock.json 파일 내 충돌이 너무 많아서, 
커밋에서 제외하였습니다. 
- 스토리북 관련 eslint 파일이 있었지만, 현재 사용 중인 스토리북과 버전 충돌 문제로 제외하였습니다. 
- **package.json에서 직접 설치하지 않은 파일이 2개인데, testing-library/dom과 ts-node 입니다.  
다른 애드온들이 의존하여 설치 되었거나 
스토리북 설정 파일을 타입스크립트로 쓸 때 일부 빌드 도구에서 사용했을 가능성이 있다고 합니다.**
> [Feat] 스토리북 설치, 설정 변경, 스토리북 컴포넌트 추가

- components/domain/auth/LoginForm.tsx
- components/domain/auth/SignUpForm.tsx
- constants/utils/errors.ts
- services/fetchWrapper.ts
close #56 
close #30 
close #44 
| 기능      | 스크린샷              |
| --------- | --------------------- |
| 로그인에러(1) |  <img width="941" alt="스크린샷 2025-06-03 오전 12 54 40" src="https://github.com/user-attachments/assets/22727650-afa5-4731-8507-d900ce50f0a1" /> | 
| 로그인에러(2) | <img width="941" alt="스크린샷 2025-06-03 오전 12 54 49" src="https://github.com/user-attachments/assets/7a0e8647-964a-409f-a5c3-917665bb7dd7" /> |
| 회원가입 중복체크 | <img width="941" alt="스크린샷 2025-06-03 오전 12 55 33" src="https://github.com/user-attachments/assets/3cdc2ae0-3bdb-4f13-bb1f-77f5eb1cdec6" /> |
> 추후 모달이 수정되는 경우 수정사항 반영하도록 하겟습니다
> [Feat] 이메일 중복체크, 모달 연결, 커스텀 에러

- components/domain/activityDetail/ActivityDetailHeader.tsx
- components/domain/activityDetail/DropdownActivityDetail.tsx
- package-lock.json
- public/ic_kebab_menu.svg
> 체험 상세 수정/삭제 Dropdown 연결
| 기능      | 스크린샷              |
| --------- | --------------------- |
| 케밥버튼 클릭 시 | ![image](https://github.com/user-attachments/assets/809bc239-0633-48d7-acb2-59bd48b63edc) |
| --------- | --------------------- |
| 수정하기 클릭 시 |![image](https://github.com/user-attachments/assets/15406981-c343-4a17-aed7-46c78f61f9aa) |
| --------- | --------------------- |
| 삭하기 클릭 시 | ![image](https://github.com/user-attachments/assets/07a995d0-7e65-4554-9696-8f37e534a524)|
> #26 체험 상세 헤더 구현
> ![image](https://github.com/user-attachments/assets/a0c41dc8-30ac-46ea-b807-c91ae2025086)
> 모달 버튼 간격이 저만 이러는 걸까요...?😢
> [Feat] 체험 상세 수정/삭제 Dropdown 연결

- app/profile/activities/new/page.tsx
- components/common/DatePicker.tsx
- components/domain/activity/ActivityCard.tsx
> 내 체험 관리 UI 생성
시간 30분으로 체크하지는 않았고 않은 이유는 바꾸는게 어려운 작업은 아니라 일단 보고 다시 논의를 나눠도 좋다고 생각하였음
const minutes = [0]; // 10분 30분 추가할 수 있음 이 코드에 30 을 추가하면 됩니다.
> [Feat]: 내 체험 관리 UI

- app/profile/activities/new/page.tsx
>일정 겹치게 만들면 차단 기능 구현 
- 일정을 겹치게 만들면 alret을 띄우면서 겹치지 말게 하라고 경고함 
alret으로 했는데 모달로 사용하는게 맞지 않나 생각함 이후 여유있을 때 수정할 생각있음
> [Feat]: 일정 겹치게 만들면 차단 기능 구현

- app/profile/activities/new/page.tsx
>  내 체험 등록 필수 항목 설정
-제목, 카테고리, 설명, 가격, 주소, 예약 가능한 시간대, 배너 이미지 필수적용
모달이나 alert으로 나올수도 있으나 기본이 UI 적으로 가장 깔끔하다고 판단하였음.
alret이나 modal로 나오게 되면 사용자가 하나하나씩 위에서부터 읽어서 안적은곳을 찾아야 하는 반면
require로 하면 어떤 부분을 적어야 하는지 바로 보여주기 때문에 require을 최종적으로 선택하였음.
단 달력에서 dropdownmenu를 사용하는데 require 를 먹이지 않아서 따로 시간과 함께 alert조건을 걸어두었음 
그리고 직전 브랜치 작업의 약간의 오타를 수정하였음
> [Feat]: 내 체험 등록 필수 항목 설정

- app/profile/activities/new/page.tsx
- package-lock.json
- package.json
> 주소창 daum api 연결
상세주소는 입력이 불가능해서 입력 폼을 2개로 만들었습니다.
npm install 한번 부탁드립니다.  https://www.npmjs.com/package/react-daum-postcode 설치하였습니다
> [Feat]: 주소창 daum api 연결

- app/profile/activities/new/page.tsx
>내 체험 등록 병합 충돌 처리를 잘못하였는데 복구하였습니다.
- [X ] 버그 수정
> [Fix]: 병합충돌 처리를 잘못했는데 복구하였음

- app/activities/[activityId]/ReservationSection.tsx
- app/activities/[activityId]/page.tsx
- app/oauth/callback/client-processing/page.tsx
- app/profile/schedule/page.tsx
- components/common/Input.tsx
- components/domain/profile/MyInfoForm.tsx
- components/domain/schedule/ReservationModal.tsx
- components/stories/Input.stories.tsx
- package-lock.json
- package.json
- api 요청에 인수가 제대로 전달되도록 수정
- 타입 에러 발생한 것들 적절한 타입이 전달되게 수정
- 서버 컴포넌트에서 api요청 시 accessToken이 필요한 걸 전달하도록 수정
> fix: release 0.1배포 중 오류 수정

- components/common/CommonButton.tsx
> 공통 버튼 컴포넌트 누락된 스타일 반영
- [] 새로운 기능 추가
| 기능      | 스크린샷              |
| --------- | --------------------- |
| 기존 버튼 | ![image](https://github.com/user-attachments/assets/f57d9e61-6860-47c6-a441-71b5dfaebe19) |
| 수정 후 | ![image](https://github.com/user-attachments/assets/d6f26a8e-60e7-4f1e-a9cb-abbf65085477) |
> https://github.com/CIrcle0616/global_nomad/issues/68
> style: 공통 버튼 컴포넌트 스타일 수정

- app/profile/activities/new/page.tsx
- services/activities.ts
✨ PR 개요
체험 등록하기 구현
🧩 PR 요약
[x]새로운 기능 추가
🎯 작업 내용 상세 (요구사항 확인)
체험 등록하기 버튼을 누르면 서버로 전송함
고민 중인 포인트나 논의가 필요한 부분이 있다면 작성해주세요.
try catch 같은 기능은 일단 없음, 코드 리팩토링 필요, 또한 등록하기 눌렀을때 계속 등록하기 홈페이지를 보여주면 어색해서 새로고침이나 다른 페이지로 옮겨가야 하나 고민
> [Feat] 체험등록 기능 추가 

- app/profile/activities/page.tsx
- components/domain/activity/ActivityCard.tsx
- components/domain/activityDetail/DropdownActivityDetail.tsx
카드 스타일 수정 
카드 스타일 수정 하였음 및 여러 가지 코드를 최신화 시켰음 
케밥 버튼이 더이상 우측으로 가지 않는게 고민...  또한 케밥버튼 사용 시 전에없던 오류가 뜹니다 ... 예진님 코드 수정하면 다시 테스트 해볼예정임 스샷에서는 보이지 않으나 제 담당 코드에선 문제없음..
> style: 카드 스타일 수정 

- app/profile/schedule/page.tsx
- components/common/gnb/Gnb.tsx
- components/common/gnb/NotificationCard.tsx
- components/common/gnb/NotificationList.tsx
- components/common/gnb/ProfileButton.tsx
- hooks/useLogin.ts
- services/fetchWrapper.ts
> hotfix: 로그아웃 로직 추가

- app/(main)/profile/activities/[activityId]/edit/page.tsx
- app/(main)/profile/activities/new/page.tsx
- components/domain/activity/ActivityCard.tsx
>케밥버튼 크기 키움 
선택 날짜가 오늘 날짜보다 전이라면 alret을 띄어주고 막음 
- [x ] 버그 수정
>케밥버튼 크기 키움 
선택 날짜가 오늘 날짜보다 전이라면 alret을 띄어주고 막음
> [Fix]: 케밥 버튼 스타일 수정 및 날짜 선택 버그 수정

- components/common/gnb/ProfileButton.tsx
- lib/queryKeys.ts
lib/queryKeys.ts 파일에 쿼리키를 생성하는 함수를 작성했습니다. 쿼리키를 일괄적으로 적용하기엔 로직 수정이 많아서 쿼리키만 생성했습니다.
> feat: 쿼리키 추가, 오류 수정

- app/(auth)/signup/page.tsx
- app/(main)/layout.tsx
- components/common/gnb/AlarmButton.tsx
- components/common/gnb/Gnb.tsx
- components/common/gnb/ProfileButton.tsx
- components/domain/activity/Search.tsx
- components/domain/mainPage/MainPageActivityListSection.tsx
- components/domain/mainPage/PopularActivitySection.tsx
- components/domain/mainPage/activityList/MainPagination.tsx
- components/domain/mainPage/activityList/taps/CategoryTabs.tsx
- components/domain/mainPage/activityList/taps/SortDropdown.tsx
- components/domain/mainPage/mainBanner/BannerDescription.tsx
- components/domain/mainPage/popularActivities/OverlayDescription.tsx
- tailwind.config.ts
> gnb, 메인, 회원가입 페이지 스타일 수정
> ex) #123 - 모달 UI 문제 이슈
이미 충분히 디자인이 반영되어있어서 사이즈 일부분만 수정하였습니다. 확인해주시면 감사합니다!
> style: gnb, 메인, 회원가입 페이지 UI 수정

- components/domain/activity/ActivityCard.tsx
- components/domain/activityDetail/reservation/ReservationClientWrapper.tsx
- components/domain/activityDetail/reservation/ReservationMobile.tsx
- components/domain/activityDetail/reservation/ReservationPC.tsx
- components/domain/activityDetail/reservation/ReservationTablet.tsx
- components/domain/reservation/ReservationCard.tsx
- components/skeleton/SkeletonCard.tsx
> 예약내역,예약 상세 페이지 UI 수정
왼쪽 수정전, 오른쪽 수정 후 
상단 수정전, 하단 수정 후 
> ex) #123 - 모달 UI 문제 이슈
> style: 예약내역,예약 상세 페이지 UI 수정
